FROM yiluxiangbei/centos7-bigdata-datax

RUN mkdir -p /home/datax-web

COPY ./datax-admin-2.1.2.jar /home/datax-web/datax-admin.jar

WORKDIR /home/datax-web

COPY application-admin.yml /home/datax-web/application.yml

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","datax-admin.jar"]